# Generated by Django 6.0.3 on 2026-03-23 20:19

import apps.bbcs.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do plano')),
                ('fee_table', models.JSONField(verbose_name='Tabela de taxas')),
                ('settlement_table', models.JSONField(verbose_name='Tabela de prazos')),
                ('is_default', models.BooleanField(default=False, verbose_name='Plano padrão')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor bruto')),
                ('platform_fee_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Taxa da plataforma')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor líquido')),
                ('payment_method', models.CharField(choices=apps.bbcs.models.PaymentMethodEnum.choices, max_length=10, verbose_name='Método de pagamento')),
                ('installments', models.PositiveSmallIntegerField(default=1, verbose_name='Parcelas')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='Moeda')),
                ('status', models.CharField(choices=apps.bbcs.models.PaymentStatusEnum.choices, default=apps.bbcs.models.PaymentStatusEnum['CAPTURED'], max_length=20, verbose_name='Status')),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Chave de idempotência')),
                ('idempotency_payload_hash', models.CharField(max_length=64, verbose_name='Hash do payload')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Payload original')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('idempotency_key', 'idempotency_payload_hash'), name='unique_idempotency_key_payload_hash')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('recipient_id', models.CharField(max_length=255, verbose_name='ID do recebedor')),
                ('role', models.CharField(max_length=50, verbose_name='Papel')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='bbcs.payment', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
