# Generated by Django 6.0.3 on 2026-03-24 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('document', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('role', models.CharField(choices=[('Industria', 'Indústria'), ('distributor', 'Distribuidor'), ('coproducer', 'Coprodutor')], max_length=20, verbose_name='Papel')),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ID externo')),
                ('bank_account', models.JSONField(blank=True, null=True, verbose_name='Dados bancários')),
            ],
            options={
                'verbose_name': 'Recebedor',
                'verbose_name_plural': 'Recebedores',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('document', 'external_id'), name='unique_recipient_document_external_id')],
            },
        ),
    ]
