# Generated by Django 6.0.3 on 2026-03-23 20:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('type', models.CharField(choices=[('payment_captured', 'Pagamento capturado')], db_index=True, max_length=100, verbose_name='Tipo do evento')),
                ('payload', models.JSONField(verbose_name='Payload do evento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('published', 'Publicado'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
            ],
            options={
                'verbose_name': 'Evento Outbox',
                'verbose_name_plural': 'Eventos Outbox',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='outbox_status_created_idx')],
            },
        ),
    ]
